---
channel: stable
addons:
  hass_tunnel:
    repository: hassio-addons/hass_tunnel
    target: hass_tunnel
    image: hass_tunnel
  zwave_js:
    repository: hassio-addons/zwave_js
    target: zwave_js
    image: zwave_js
